config/routes.rb
Rails.application.routes.draw do
  root to: 'rooms#show'
  get 'login', to: 'users#login', as: :login
  # get 'rooms', to: 'rooms#show', as: :rooms

  # root to: 'users#login'
  # get 'rooms', to: 'rooms#show', as: :rooms

  resources :rooms do
    member do
      get :start_chat
    end
  end
  resources :users do
    collection do
      post :login
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  # Serve websocket cable requests in-process
  mount ActionCable.server => '/cable'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/message.rb
class Message < ApplicationRecord
  after_create_commit { MessageBroadcastJob.perform_later self}

  belongs_to :user

end

app/models/user.rb
class User < ApplicationRecord
  validates :name, presence: true

  has_many :messages
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
 
  def authenticate_user
    redirect_to :login unless current_user
  end

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end
  helper_method :current_user

end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_filter :authenticate_user
  before_filter :load_sender, only:[:show, :start_chat]
  before_filter :load_receiver, only:[:start_chat]

  def show
    @users = User.all.where.not(id: current_user.id)
  end

  def start_chat
    @messages = Message.all.where(user_id: [@sender.id, @receiver.id], receiver_id: [@sender.id, @receiver.id])
  end

  private

  def load_sender
    @sender = current_user
  end

  def load_receiver
    @receiver = User.find_by(id: params[:id])
    unless @receiver
      redirect_to :root_path   
    end
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def login
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    @user.save
    session[:user_id] = @user.id
    cookies[:user_id] = @user.id
  end

  private

  def user_params
    params.require(:user).permit(:name)
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AcDemo</title>
    <%= csrf_meta_tags %>
    <%= action_cable_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <link href='https://fonts.googleapis.com/css?family=PT+Sans' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Satisfy' rel='stylesheet' type='text/css'>
  </head>

  <body style="background: url('assets/background.jpg') no-repeat center center; background-size:(100%); filter:alpha(opacity=50);">
    <nav class="navbar" style="border-bottom: 1px solid #f8f8f8;">
      <div class="container-fluid">
        <div class="navbar-header">
          <a class="navbar-brand" href="#" style="color:#ffffff;">Chat Room</a>
          <ul class="nav navbar-nav" style="float:right; color:white; padding:15px;">
            <li><i class="fa fa-user"></i> <%= current_user.name if current_user %> </li>
          </ul>
        </div>
      </div>
    </nav>
    <%= yield %>
  </body>
</html>

app/views/messages/_message.html.erb
<div class="message" title="<%= message.created_at.in_time_zone.localtime.strftime(' %I : %M %p') %>">
  <div id="usertext_<%= message.user_id %>" class="talk-bubble tri-right <%= (current_user.id == message.user_id) ? 'btm-right-in pull-right' : 'btm-left-in'%> ">
    <div class="talktext">
      <span class="bubble_user_icon <%= current_user.id == message.user_id ? 'hide' : '' %>"><%= @receiver.present? ? @receiver.name.first : "" %></span>
      <span id="sender_id" class="hide"><%= message.user_id %></span>
      <span id="receiver_id" class="hide"><%= message.receiver_id %></span>
      <p><%= message.content %></p>
      <span id="created_at" class="hide"><%= message.created_at %></span>
    </div>
  </div>
</div>

app/views/rooms/_start_chat.html.erb
<div class="chat-box">
  <div class="chat_user_title" id="receiver_name"><%= @receiver.name %></div>
  <span id="msg_sender_id" class="hide"><%= @sender.id %></span>
  <div id="messages">
    <div id="user_<%= @receiver.id %>">
      <% if @messages.present? %>
        <div style="width:100%; text-align:center; padding:1px; color:gray;">
          <hr/>
          Started from: <%= @messages.first.created_at.strftime('%A, %d/%m/%Y') %>
        </div>
        <%= render partial: "messages/message", locals:{message: @messages.first} %>
      <% end %>
      <% @messages.each_cons(2) do |pre_message, message| %>
        <% if pre_message.created_at.strftime('%d-%m-%Y') == message.created_at.strftime('%d-%m-%Y') %>
          <%= render partial: "messages/message", locals:{message: message} %>
        <% else %>
          <div style="width:100%; text-align:center; padding:1px; color:gray;">
            <hr/>
            <%= message.created_at.strftime('%A, %d/%m/%Y') %>
          </div>
          <%= render partial: "messages/message", locals:{message: message} %>
        <% end %>
      <% end %>
    </div>
  </div>
  <form>
    <textarea data-behavior="room_speaker" class="input-message" placeholder="Some text" cols="40" rows="2" name="textarea" id="textarea"></textarea>
    <%= hidden_field_tag "sender", @sender.id, id:"user" %>
    <%= hidden_field_tag "receiver", @receiver.id, id:"receiver" %>
  </form>
</div>
<script>
  scrollItNow()
</script>

app/views/rooms/show.html.erb
<div class="col-xs-9">
  <div class="chat-room-show" id="start_chat">
    <h4> Welcome to Chat Room</h4>
  </div>
</div>
<div class="col-xs-3 user-list">
  <% @users.each do |user|%>
    <div class="chat-room-user">
      <%= link_to start_chat_room_path(user.id), remote: true, class: "user-chat-link" do %>
        <i class="fa fa-user"></i> &nbsp;&nbsp;&nbsp; <%= user.name %>   <div id="noti_<%= user.id %>" class="notification hide"></div>
      <% end %>
    </div>
  <% end %>
</div>

app/views/rooms/start_chat.js.erb
$("#start_chat").html("<%= j render(partial: 'start_chat', locals:{messages: @messages})%>");

// removing notification count if any on right side user's list, on user's click.
$('#noti_<%= @receiver.id %>').html("");
$('#noti_<%= @receiver.id %>').addClass("hide");
$('#messages').css('height',$(window).height() - 200);
$('.user-list').css('height',$(window).height()- 55);

app/views/users/create.js.erb
<% if @user.errors.present? %>
  $("label").html("Please enter your name first");
<% else %>
  window.location.href = "<%= root_path %>";
<% end %>

app/views/users/login.html.erb
<div class="login_form">
  <div class="col-xs-6">
    <hgroup>
      <img src="assets/logo.png" width="150" alt="logo">
      <h1>Start Free Chat</h1>
      <hr/>
      <ul>
        <li>Login is signup, if you previously logged in via same email then you can avoid Screen Name. &nbsp;&nbsp;&nbsp;&nbsp;<i class='fa fa-star'></i> </li>
        <li>No password reset feature. &nbsp;&nbsp;&nbsp;&nbsp;<i class='fa fa-star'></i> </li>
        <li>Lorem ipsum dolor sit amet, elit mi nam, sed ultrices eu urna a. Class nulla. &nbsp;&nbsp;&nbsp;&nbsp;<i class='fa fa-star'></i> </li>
      </ul>
    </hgroup>
  </div>
  <div class="col-xs-6" style="border-left: 1px solid #cccccc;">
    <%= form_for @user, remote: true do |f|%>
      <div class="group">
        <%= f.text_field :name, data: {errorkey: "name"} %>
        <span class="highlight"></span><span class="bar"></span>
        <label>Screen Name</label>
      </div>
      <div class="group">
        <%= f.text_field :name, data: {errorkey: "name"} %>
        <span class="highlight"></span><span class="bar"></span>
        <label>Email</label>
      </div>
      <div class="group">
        <%= f.password_field :name, data: {errorkey: "name"} %>
        <span class="highlight"></span><span class="bar"></span>
        <label>Password</label>
      </div>
      <%= f.submit "Login", class: "button buttonBlue" do %>
        Subscribe
        <div class="ripples buttonRipples"><span class="ripplesCircle"></span></div>
      <% end %>
    <% end %>
  </div>
</div>